# Generated by Django 4.2.1 on 2023-05-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default='2023-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(default=234567890987),
            preserve_default=False,
        ),
    ]
