# Generated by Django 4.2.1 on 2023-05-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='birth_date',
            field=models.DateField(default='2022-3-4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='mobile',
            field=models.IntegerField(default=8765432),
            preserve_default=False,
        ),
    ]
